services:
#swag-service
    swag:
      image: lscr.io/linuxserver/swag:latest
      container_name: swag_vps
      cap_add:
        - NET_ADMIN
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/Argentina/Buenos_Aires
        - URL=${DOMINIO}
        - VALIDATION=dns
        - DNSPLUGIN=duckdns
        - SUBDOMAINS=
      volumes:
        - ./swag:/config
      ports:
        - ${PUERTO}:443/tcp
        - 80:80
      restart: unless-stopped
#influxdb-service
    influxdb:
      image: influxdb:latest
      container_name: influxdb_vps
      volumes:
        - ./influx_data:/var/lib/influxdb2
      environment:
        - DOCKER_INFLUXDB_INIT_MODE=setup
        - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER}
        - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
        - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
        - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
        - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
        - INFLUXD_UI_BASE_PATH=/influxdb/
      ports:
        - 8086:8086
      restart: unless-stopped
#grafana-service
    grafana:
      image: grafana/grafana-oss:13.0.1
      container_name: grafana_vps
      ports:
        - 3000:3000
      volumes:
        - ./grafana:/var/lib/grafana
      environment:
        GF_SERVER_PROTOCOL: http
        GF_SERVER_ROOT_URL: https://${DOMINIO}:${PUERTO}/grafana/
        GF_SERVER_SERVE_FROM_SUB_PATH: "true"
        GF_SERVER_DOMAIN: ${DOMINIO}
        GF_ANALYTICS_REPORTING_ENABLED: "false"
        GF_FEATURE_TOGGLES_ENABLE: canvasPanelPanZoom,canvasPanelLayers
      restart: unless-stopped
      depends_on:
        - influxdb